In [22]:
import math
from typing import Optional

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor

from typing import Tuple

import torch

from mamba_ssm.modules.mamba_simple import Mamba
import sys
from vim import models_mamba

import math
from typing import Optional

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor

from einops import rearrange, repeat
from tome.merge import bipartite_soft_matching, merge_source, merge_wavg
def compare_tensors(self,t1,t2):
        t1_slice = t1[0, :30, :]
        t2_slice = t2[0, :30, :]
        
        # Calculating the Euclidean distance for each of the first 30 tokens
        distances = torch.norm(t1_slice - t2_slice, dim=-1)
        
        # Convert distances to a list (optional)
        distances_list = distances.tolist()
        
        # Output the distances
        print(distances_list)
x = torch.tensor([[[1.0, 0.0], 
                   [3,-1],# Token 1
                   [12.0, 10.0],   # Token 2
                   [1, 10],   # Token 3
                   [11.0, 10.0],   # Token 4
                   [10, 10],
                   [0, 1]], 
                  [[1.0, 0.0], 
                   [3,-1],# Token 1
                   [12.0, 10.0],   # Token 2
                   [1, 10],   # Token 3
                   [11.0, 10.0],   # Token 4
                   [10, 10],
                   [0, 1]]
                 ])
print(x.shape)
merge, _,_ =  bipartite_soft_matching(
                x,
                2,
                False,
                False,
            )
x_new = merge(x)
# distances = torch.norm(x[:,:-1,:]-x_new,dim=-1)
# print(distances)
print(f"x new {x_new}")

torch.Size([2, 7, 2])
Initial x tensor:
tensor([[[ 1.,  0.],
         [ 3., -1.],
         [12., 10.],
         [ 1., 10.],
         [11., 10.],
         [10., 10.],
         [ 0.,  1.]],

        [[ 1.,  0.],
         [ 3., -1.],
         [12., 10.],
         [ 1., 10.],
         [11., 10.],
         [10., 10.],
         [ 0.,  1.]]])
src tensor:
tensor([[[ 1.,  0.],
         [12., 10.],
         [11., 10.],
         [ 0.,  1.]],

        [[ 1.,  0.],
         [12., 10.],
         [11., 10.],
         [ 0.,  1.]]])
dst tensor:
tensor([[[ 3., -1.],
         [ 1., 10.],
         [10., 10.]],

        [[ 3., -1.],
         [ 1., 10.],
         [10., 10.]]])
unm_idx tensor:
tensor([[[3],
         [0]],

        [[3],
         [0]]])
unm tensor:
tensor([[[0., 1.],
         [1., 0.]],

        [[0., 1.],
         [1., 0.]]])
src_idx tensor:
tensor([[[2],
         [1]],

        [[2],
         [1]]])
src (after gather) tensor:
tensor([[[11., 10.],
         [12., 10.]],

        [[11., 10.],


In [2]:
scores tensor([[[0.0000, 0.6402],
         [0.7071, 0.9959],
         [0.8137, 0.9972]],

        [[0.0000, 0.6402],
         [0.7071, 0.9959],
         [0.8137, 0.9972]]])
node_maxtensor([[  -inf, 0.9959, 0.9972],
        [  -inf, 0.9959, 0.9972]])
node_idxtensor([[0, 1, 1],
        [0, 1, 1]])
edge_idx`n tensor([[[2],
         [1],
         [0]],

        [[2],
         [1],
         [0]]])
unm_idx`n tensor([[[1],
         [0]],

        [[1],
         [0]]])
src_idx`n tensor([[[2]],

        [[2]]])
dst_idx`n tensor([[[1]],

        [[1]]])
Initial x tensor:
tensor([[[ 1.0000,  0.0000],
         [ 0.0000, 10.0000],
         [ 0.4000,  0.4000],
         [ 0.5000,  0.6000],
         [ 0.5000,  0.7000]],

        [[ 1.0000,  0.0000],
         [ 0.0000, 10.0000],
         [ 0.4000,  0.4000],
         [ 0.5000,  0.6000],
         [ 0.5000,  0.7000]]])
src tensor:
tensor([[[1.0000, 0.0000],
         [0.4000, 0.4000],
         [0.5000, 0.7000]],

        [[1.0000, 0.0000],
         [0.4000, 0.4000],
         [0.5000, 0.7000]]])
dst tensor:
tensor([[[ 0.0000, 10.0000],
         [ 0.5000,  0.6000]],

        [[ 0.0000, 10.0000],
         [ 0.5000,  0.6000]]])
unm_idx tensor:
tensor([[[0],
         [1]],

        [[0],
         [1]]])
unm tensor:
tensor([[[1.0000, 0.0000],
         [0.4000, 0.4000]],

        [[1.0000, 0.0000],
         [0.4000, 0.4000]]])
src_idx tensor:
tensor([[[2]],

        [[2]]])
src (after gather) tensor:
tensor([[[0.5000, 0.7000]],

        [[0.5000, 0.7000]]])
dst_idx tensor:
tensor([[[1]],

        [[1]]])
dst (after scatter_reduce) tensor:
tensor([[[ 0.0000, 10.0000],
         [ 0.5000,  0.6500]],

        [[ 0.0000, 10.0000],
         [ 0.5000,  0.6500]]])
Final result tensor:
tensor([[[ 1.0000,  0.0000],
         [ 0.0000, 10.0000],
         [ 0.4000,  0.4000],
         [ 0.5000,  0.6500]],

        [[ 1.0000,  0.0000],
         [ 0.0000, 10.0000],
         [ 0.4000,  0.4000],
         [ 0.5000,  0.6500]]])
tensor([[0.0000, 0.0000, 0.0000, 0.0500],
        [0.0000, 0.0000, 0.0000, 0.0500]])
x new tensor([[[ 1.0000,  0.0000],
         [ 0.0000, 10.0000],
         [ 0.4000,  0.4000],
         [ 0.5000,  0.6500]],

        [[ 1.0000,  0.0000],
         [ 0.0000, 10.0000],
         [ 0.4000,  0.4000],
         [ 0.5000,  0.6500]]])

SyntaxError: invalid syntax (1950194434.py, line 1)

In [ ]:
import torch

# Example tensor
input = torch.tensor([[1, 2], [3, 4], [5, 6]])

# Indices to gather
index = torch.tensor([[0, 1], [2, 0], [1, 0]])

# Gather elements from input according to index
output = torch.gather(input, 0, index)

print(output)

In [8]:
import torch

# Step 1: Create the original tensor
tensor = torch.randn(20, 20, 20)

# Step 2: Define the index tensor
idx_tensor = torch.tensor([10, 15])

# Step 3: Remove the specified indices
mask = torch.ones(tensor.size(1), dtype=torch.bool)
mask[idx_tensor] = False
reduced_tensor = tensor[:, mask, :]

# Step 4: Check the shape of the resulting tensor
print(reduced_tensor.shape)  # Expected output: torch.Size([20, 18, 20])


torch.Size([20, 18, 20])


In [7]:
import torch

# Step 1: Create the original tensor
tensor = torch.randn(20, 20, 20)

# Step 2: Define the index tensor
idx_tensors = torch.tensor([[10, 15]] * 20)  # Shape [20, 2]
print(idx_tensors.shape)
# Step 3: Create a mask for each slice
mask = torch.ones(tensor.size(1), dtype=torch.bool)  # Create a mask for the second dimension
mask[idx_tensors] = False  # Set the positions to be removed as False
print(mask.shape)
# Step 4: Apply the mask to the tensor
# Use broadcasting and advanced indexing to apply the mask across all slices
reduced_tensor = tensor[:, mask, :]

# Step 5: Check the shape of the resulting tensor
print(reduced_tensor.shape)  # Expected output: torch.Size([20, 18, 20])


torch.Size([20, 2])
torch.Size([20])
torch.Size([20, 18, 20])


In [18]:
def test_reduce_tensor():
    # Manually created tensor of shape [2, 3, 2]
    tensor = torch.tensor([
        [[1, 2], [3, 4], [5, 6]],  # First slice
        [[7, 8], [9, 10], [11, 12]]  # Second slice
    ])
    print(tensor.shape)
    # Indices to remove from the second dimension for each slice
    idx_tensors = torch.tensor([[0, 2], [1, 2]])  # Different indices for each slice
    print(idx_tensors.shape)
    
    # Expected tensor after removing specified indices
    expected_tensor = torch.tensor([
        [[3, 4]],  # After removing indices 0 and 2 from the first slice
        [[7, 8]]   # After removing indices 1 and 2 from the second slice
    ])
    
    # Mask creation and application
    mask = torch.ones(tensor.size(0), tensor.size(1), dtype=torch.bool)
    mask[torch.arange(2).unsqueeze(1), idx_tensors] = False

    print(mask.shape)
    # reduced_tensor = tensor[torch.arange(2).unsqueeze(1), mask].view(2, 1, 2)
    reduced_tensor = tensor[torch.arange(2)[:, None], mask]
    # Check if the output matches the expected tensor
    print(reduced_tensor.shape)
    assert torch.equal(reduced_tensor, expected_tensor), f"Test failed: {reduced_tensor} != {expected_tensor}"
    
    print("Test passed successfully!")

# Run the test
test_reduce_tensor()


torch.Size([2, 3, 2])
torch.Size([2, 2])
torch.Size([2, 3])


IndexError: The shape of the mask [2, 3] at index 0 does not match the shape of the indexed tensor [2, 3, 2] at index 1

In [19]:
import torch

# Step 1: Create the original tensor with shape [20, 20, 20]
tensor = torch.randn(20, 20, 20)

# Step 2: Define idx_tensors, which contains indices to be removed for each batch
# For example, we're removing the 10th and 15th indices from each 20x20 slice
idx_tensors = torch.tensor([[10, 15]] * 20)  # Repeat the same indices for each slice
print(idx_tensors.shape)
# Step 3: Create a boolean mask initialized to True for all positions
mask = torch.ones(tensor.size(0), tensor.size(1), dtype=torch.bool)

# Use advanced indexing to set False in the mask where idx_tensors indicates
# mask[i, idx_tensors[i, :]] is set to False for the corresponding batch
mask[torch.arange(20).unsqueeze(1), idx_tensors] = False
print(mask.shape)
# Step 4: Apply the mask to the original tensor
# tensor[torch.arange(20)[:, None], mask] filters out the unwanted indices in the second dimension
reduced_tensor = tensor[torch.arange(20)[:, None], mask]

# Step 5: Verify the shape of the resulting tensor
print(reduced_tensor.shape)  # Expected output: torch.Size([20, 18, 20])


torch.Size([20, 2])
torch.Size([20, 20])
torch.Size([20, 360])


In [20]:
import torch

def test_reduce_tensor():
    # Manually created tensor of shape [2, 3, 2]
    tensor = torch.tensor([
        [[1, 2], [3, 4], [5, 6]],  # First slice
        [[7, 8], [9, 10], [11, 12]]  # Second slice
    ])
    print("Tensor shape:", tensor.shape)

    # Indices to remove from the second dimension for each slice
    idx_tensors = torch.tensor([[0, 2], [1, 2]])  # Different indices for each slice
    print("idx_tensors shape:", idx_tensors.shape)
    
    # Expected tensor after removing specified indices
    expected_tensor = torch.tensor([
        [[3, 4]],  # After removing indices 0 and 2 from the first slice
        [[7, 8]]   # After removing indices 1 and 2 from the second slice
    ])
    
    # Mask creation and application
    mask = torch.ones(tensor.size(0), tensor.size(1), dtype=torch.bool)
    mask[torch.arange(2).unsqueeze(1), idx_tensors] = False
    print("Mask shape:", mask.shape)

    # Apply the mask correctly
    reduced_tensor = tensor[torch.arange(2)[:, None], mask].view(2, 1, 2)

    # Check if the output matches the expected tensor
    print("Reduced tensor shape:", reduced_tensor.shape)
    print("Reduced tensor:", reduced_tensor)
    assert torch.equal(reduced_tensor, expected_tensor), f"Test failed: {reduced_tensor} != {expected_tensor}"
    
    print("Test passed successfully!")

# Run the test
test_reduce_tensor()


Tensor shape: torch.Size([2, 3, 2])
idx_tensors shape: torch.Size([2, 2])
Mask shape: torch.Size([2, 3])


IndexError: The shape of the mask [2, 3] at index 0 does not match the shape of the indexed tensor [2, 3, 2] at index 1